name: Reusable workflow for 2 level of nested matrices
on:
  workflow_call:
    inputs:
      versions:
        description: "Versions"
        required: true
        type: string
      use-cache:
        type: boolean
        description: "Whether to cache the gradle caches (don't use for a 100+ version run)"
        required: false
        default: true
  workflow_dispatch:
    inputs:
      versions:
        description: "Versions eg: [\"21.10.62\", \"21.10.64\"]"
        required: true
        type: string
      use-cache:
        type: boolean
        description: "Whether to cache the gradle caches (don't use for a 100+ version run)"
        required: false
        default: false

jobs:
  neo-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Don't fail fast to avoid locking TF State
      matrix:
        neo-version: ${{ fromJSON(inputs.versions) }}
    name: neoforge ${{ matrix.neo-version }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: 'NotStirred/dasm-mod-neoforge-ci'
      - uses: actions/cache@v4
        if: inputs.use-cache == true
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ matrix.neo-version }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-${{ matrix.neo-version }}-

      - name: download neo jar
        uses: actions/download-artifact@v4
        with:
          name: neo-jar
          path: runs/server/mods/

      - name: create eula file
        run: echo eula=true > runs/server/eula.txt

      - name: run test
        run: "CI=true NEO_VERSION=${{ matrix.neo-version }} ./gradlew runServer"
