name: Reusable workflow for 2 level of nested matrices
on:
  workflow_call:
    inputs:
      versions:
        description: "Versions"
        required: true
        type: string

jobs:
  neo-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Don't fail fast to avoid locking TF State
      matrix:
        neo-version: ${{ fromJSON(inputs.versions) }}
    name: neoforge (${{ matrix.version }})
    steps:
      - uses: actions/checkout@v6
        with:
          repository: 'NotStirred/dasm-mod-neoforge-ci'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: download neo jar
        uses: actions/download-artifact@v4
        with:
          name: neo-jar
          path: runs/server/mods/

      - name: create eula file
        run: echo eula=true > runs/server/eula.txt

      - name: run test
        run: "CI=true NEO_VERSION=${{ matrix.neo-version }} ./gradlew runServer"
